export const categories = [
    { id: "all", name: "All Items", path: "/menu" },
    { id: "breakfast", name: "Breakfast", path: "/menu/breakfast" },
    { id: "lunch", name: "Lunch", path: "/menu/lunch" },
    { id: "dinner", name: "Dinner", path: "/menu/dinner" },
    { id: "supper", name: "Supper", path: "/menu/supper" },
    { id: "snacks", name: "Snacks", path: "/menu/snacks" },
    { id: "beverages", name: "Beverages", path: "/menu/beverages" },
    { id: "desserts", name: "Desserts", path: "/menu/desserts" },
  ]
  
  // This is a fallback in case the API fails
  export const menuItems = [
    {
      id: 1,
      name: "Chicken Sandwich",
      description: "Grilled chicken with fresh vegetables and special sauce",
      price: 5.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "lunch",
      rating: 4.8,
      tags: ["filling", "protein", "lunch", "dinner"],
    },
    {
      id: 2,
      name: "Vegetable Pasta",
      description: "Fresh pasta with seasonal vegetables and pesto sauce",
      price: 6.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "lunch",
      rating: 4.6,
      tags: ["vegetarian", "filling", "lunch", "dinner"],
    },
    {
      id: 3,
      name: "Fruit Smoothie",
      description: "Blend of fresh fruits with yogurt and honey",
      price: 3.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "beverages",
      rating: 4.9,
      tags: ["cold", "refreshing", "light", "morning"],
    },
    {
      id: 4,
      name: "Chocolate Muffin",
      description: "Freshly baked chocolate muffin with chocolate chips",
      price: 2.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "desserts",
      rating: 4.7,
      tags: ["sweet", "morning", "snack"],
    },
    {
      id: 5,
      name: "Breakfast Burrito",
      description: "Scrambled eggs, cheese, and vegetables wrapped in a tortilla",
      price: 4.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "breakfast",
      rating: 4.5,
      tags: ["filling", "protein", "morning"],
    },
    {
      id: 6,
      name: "Caesar Salad",
      description: "Fresh romaine lettuce with Caesar dressing, croutons, and parmesan",
      price: 5.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "lunch",
      rating: 4.4,
      tags: ["light", "healthy", "lunch"],
    },
    {
      id: 7,
      name: "Potato Chips",
      description: "Crispy potato chips with a sprinkle of salt",
      price: 1.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "snacks",
      rating: 4.3,
      tags: ["crunchy", "snack", "light"],
    },
    {
      id: 8,
      name: "Hot Coffee",
      description: "Freshly brewed coffee with your choice of milk and sugar",
      price: 2.29,
      image: "/placeholder.svg?height=300&width=300",
      category: "beverages",
      rating: 4.8,
      tags: ["hot", "morning", "warm"],
    },
    {
      id: 9,
      name: "Pancake Stack",
      description: "Fluffy pancakes served with maple syrup and butter",
      price: 4.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "breakfast",
      rating: 4.7,
      tags: ["sweet", "morning", "filling"],
    },
    {
      id: 10,
      name: "Chocolate Brownie",
      description: "Rich chocolate brownie with walnuts",
      price: 3.29,
      image: "/placeholder.svg?height=300&width=300",
      category: "desserts",
      rating: 4.9,
      tags: ["sweet", "dessert", "comfort"],
    },
    {
      id: 11,
      name: "Iced Tea",
      description: "Refreshing iced tea with lemon",
      price: 1.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "beverages",
      rating: 4.5,
      tags: ["cold", "refreshing", "light"],
    },
    {
      id: 12,
      name: "Granola Bar",
      description: "Healthy granola bar with nuts and dried fruits",
      price: 2.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "snacks",
      rating: 4.2,
      tags: ["healthy", "light", "morning", "snack"],
    },
    {
      id: 13,
      name: "Eggs Benedict",
      description: "Poached eggs with hollandaise sauce on English muffins",
      price: 7.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "breakfast",
      rating: 4.8,
      tags: ["protein", "morning", "filling"],
    },
    {
      id: 14,
      name: "Avocado Toast",
      description: "Smashed avocado on whole grain toast with cherry tomatoes",
      price: 6.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "breakfast",
      rating: 4.6,
      tags: ["vegetarian", "healthy", "morning"],
    },
    {
      id: 15,
      name: "Chicken Wrap",
      description: "Grilled chicken with vegetables and sauce in a tortilla wrap",
      price: 6.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "lunch",
      rating: 4.5,
      tags: ["protein", "filling", "lunch"],
    },
    {
      id: 16,
      name: "Veggie Burger",
      description: "Plant-based patty with lettuce, tomato, and special sauce",
      price: 7.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "lunch",
      rating: 4.3,
      tags: ["vegetarian", "filling", "lunch"],
    },
    {
      id: 17,
      name: "Trail Mix",
      description: "Mix of nuts, dried fruits, and chocolate pieces",
      price: 3.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "snacks",
      rating: 4.4,
      tags: ["healthy", "energy", "snack"],
    },
    {
      id: 18,
      name: "Yogurt Parfait",
      description: "Layered yogurt with granola and fresh berries",
      price: 4.29,
      image: "/placeholder.svg?height=300&width=300",
      category: "snacks",
      rating: 4.6,
      tags: ["healthy", "sweet", "morning", "snack"],
    },
    {
      id: 19,
      name: "Hot Chocolate",
      description: "Rich chocolate drink topped with whipped cream",
      price: 3.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "beverages",
      rating: 4.7,
      tags: ["hot", "sweet", "comfort"],
    },
    {
      id: 20,
      name: "Green Tea",
      description: "Freshly brewed green tea with antioxidants",
      price: 2.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "beverages",
      rating: 4.3,
      tags: ["hot", "healthy", "light"],
    },
    {
      id: 21,
      name: "Cheesecake",
      description: "Creamy cheesecake with graham cracker crust",
      price: 4.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "desserts",
      rating: 4.8,
      tags: ["sweet", "rich", "dessert"],
    },
    {
      id: 22,
      name: "Apple Pie",
      description: "Traditional apple pie with cinnamon and flaky crust",
      price: 4.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "desserts",
      rating: 4.6,
      tags: ["sweet", "comfort", "dessert"],
    },
    // Adding dinner items
    {
      id: 23,
      name: "Grilled Salmon",
      description: "Fresh salmon fillet grilled to perfection with lemon butter sauce",
      price: 12.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "dinner",
      rating: 4.9,
      tags: ["seafood", "protein", "dinner", "healthy"],
    },
    {
      id: 24,
      name: "Steak with Mashed Potatoes",
      description: "Juicy steak served with creamy mashed potatoes and seasonal vegetables",
      price: 14.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "dinner",
      rating: 4.8,
      tags: ["meat", "protein", "dinner", "filling"],
    },
    {
      id: 25,
      name: "Mushroom Risotto",
      description: "Creamy Italian rice dish with wild mushrooms and parmesan cheese",
      price: 10.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "dinner",
      rating: 4.7,
      tags: ["vegetarian", "dinner", "italian", "creamy"],
    },
    {
      id: 26,
      name: "Vegetable Curry",
      description: "Flavorful vegetable curry served with steamed rice",
      price: 9.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "dinner",
      rating: 4.6,
      tags: ["vegetarian", "spicy", "dinner", "filling"],
    },
    // Adding supper items
    {
      id: 27,
      name: "Tomato Soup",
      description: "Warm tomato soup served with grilled cheese sandwich",
      price: 7.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "supper",
      rating: 4.5,
      tags: ["warm", "comfort", "supper", "light"],
    },
    {
      id: 28,
      name: "Chicken Noodle Soup",
      description: "Hearty chicken soup with vegetables and noodles",
      price: 8.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "supper",
      rating: 4.7,
      tags: ["warm", "comfort", "supper", "protein"],
    },
    {
      id: 29,
      name: "Quiche Lorraine",
      description: "Classic quiche with bacon, cheese, and eggs in a flaky crust",
      price: 8.99,
      image: "/placeholder.svg?height=300&width=300",
      category: "supper",
      rating: 4.6,
      tags: ["protein", "supper", "french"],
    },
    {
      id: 30,
      name: "Light Pasta Primavera",
      description: "Light pasta dish with fresh spring vegetables and herbs",
      price: 9.49,
      image: "/placeholder.svg?height=300&width=300",
      category: "supper",
      rating: 4.4,
      tags: ["vegetarian", "light", "supper", "pasta"],
    },
  ]